package:
    name: detector_integration_api
    version: 1.8.3

source:
    path: ..

build:
    number: 0

requirements:
    build:
        - python

    run:
        - python
        - bottle
        - requests

about:
    home: https://github.com/datastreaming/detector_integration_api
