package:
    name: detector_integration_api
    version: 0.2.0

source:
    path: ..

build:
    number: 0

requirements:
    build:
        - python

    run:
        - python
        - bottle
        - requests
        - mflow_nodes >=1.3.0

build:
  entry_points:
    - dia_sf = detector_integration_api.deployment.sf.sf_start_server:main
    - dia_csaxs = detector_integration_api.deplyment.csaxs.csaxs_start_server:main

about:
    home: git@git.psi.ch:HPDI/integration_rest_api.git
